"""Generate the Libra Engine site's read-only tenets view from the canonical
constitution (lecg-).

The LE site's /tenets/ page renders window.TENETS_DATA (tenets/tenets-data.js).
Until now that file was a hand-maintained static snapshot -- already stale (it
stops at R14; the live law has R15) and disconnected from the source of truth.

This generator emits tenets-data.js straight from the canonical governed
constitution (governance/lecg_constitution.py), so the public tenets view is
single-sourced: complete (R1-R15), de-musked, and carrying the governance
metadata (per-item version + ratified_at, the amendment changelog, the governed
constitution_version) for the renderer to surface.

It maps the constitution to the shape the existing renderer reads:
  tier.definition_core -> definition ; tenet.core -> text ; note.title_core ->
  title ; modifier/flag/rule .core -> definition/text. Governance fields ride
  along as extra keys (the current renderer ignores them; a later pass surfaces
  the versions + changelog).

Re-run whenever the constitution changes (a ratified amendment). Permanent lecg_
tool, like lec_snapshot_golden / lec_build_format.

  python -m governance.lecg_build_tenets_view            # write to the LE site
  python -m governance.lecg_build_tenets_view --check     # diff only, no write
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from governance.lecg_constitution import load_constitution, BASELINE_DIR

# The LE site sits beside the Compass repo under Local Sites/. backend/ ->
# libra-engine-compass -> Local Sites -> libra-engine-site/tenets/tenets-data.js.
_LOCAL_SITES = Path(__file__).resolve().parent.parent.parent.parent
DEFAULT_OUT = _LOCAL_SITES / "libra-engine-site" / "tenets" / "tenets-data.js"

_HEADER = (
    "// GENERATED by governance/lecg_build_tenets_view.py from the canonical\n"
    "// constitution. Do NOT edit by hand -- re-run the generator after a ratified\n"
    "// amendment. Source of truth: libra-engine-compass governance/lecg_constitution.py\n"
)


def _gov(item: dict) -> dict:
    return {"version": item.get("version"), "ratified_at": item.get("ratified_at")}


def build_view() -> dict:
    """Map the canonical constitution to the LE site's TENETS_DATA shape."""
    c = load_constitution()
    tiers = []
    for t in c["tiers"]:
        tiers.append({
            "slug": t["slug"],
            "color_hex": t["color_hex"],
            "code": t["code"],
            "label": t["label"],
            "definition": t["definition_core"],
            "tenets": [
                {"id": x["id"], "number": x["number"], "text": x["core"], **_gov(x)}
                for x in t["tenets"]
            ],
            "notes": [
                {"title": n.get("title_core", ""), "text": n["core"], **_gov(n)}
                for n in t["notes"]
            ],
        })
    return {
        "_generated": "from the canonical constitution by governance/lecg_build_tenets_view.py; do not edit by hand",
        "constitution_version": c["constitution_version"],
        "schema_version": c["schema_version"],
        "ratified_at": c["ratified_at"],
        "tiers": tiers,
        "modifiers": [
            {"id": m["id"], "label": m["label"], "definition": m["core"], **_gov(m)}
            for m in c["modifiers"]
        ],
        "flags": [
            {"id": f["id"], "label": f["label"], "definition": f["core"], **_gov(f)}
            for f in c["flags"]
        ],
        "rules": [
            {"id": r["id"], "text": r["core"], **_gov(r)}
            for r in c["rules"]
        ],
        "changelog": c["changelog"],
    }


def render(view: dict) -> str:
    body = json.dumps(view, indent=2, ensure_ascii=True)
    return f"{_HEADER}window.TENETS_DATA = {body};\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    out = DEFAULT_OUT
    view = build_view()
    text = render(view)

    n_tiers = len(view["tiers"])
    n_tenets = sum(len(t["tenets"]) for t in view["tiers"])
    n_rules = len(view["rules"])
    print(f"  source baseline: {BASELINE_DIR}")
    print(f"  constitution_version: {view['constitution_version']}")
    print(f"  {n_tiers} tiers, {n_tenets} tenets, {n_rules} rules "
          f"({view['rules'][-1]['id']} is the last), {len(view['changelog'])} changelog entries")

    if not out.parent.exists():
        print(f"  ERROR: target dir does not exist: {out.parent}")
        return 1

    if check:
        existing = out.read_text(encoding="utf-8") if out.exists() else ""
        if existing == text:
            print(f"  --check: {out} is up to date")
            return 0
        print(f"  --check: {out} WOULD CHANGE (re-run without --check to write)")
        return 0

    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"  wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
